name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run build scripts
      run: | 
        sudo apt update
        sudo ./build-profiler.sh
        sudo ./build-viewer.sh
        chmod 755 viewer/viewer
        chmod 755 allocationTracker/ldlib.so
        chmod 755 prepareDatabase/prepareDatabase
        chmod 755 perfSqliteExport/exportToSqlite.py
        chmod 755 perfMemPlus
        chmod 755 perf
        chmod 755 setPerfEventPermissions.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: perfMemPlus
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          viewer/viewer
          allocationTracker/ldlib.so
          prepareDatabase/prepareDatabase
          perfSqliteExport/exportToSqlite.py
          perfMemPlus
          perf
          setPerfEventPermissions.sh
          
          
