name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install qt
      run: | 
        sudo apt-get install qt5-default
        sudo apt-get install libqt5charts5 #only required for viwer
    - name: make prepareDatabase
      working-directory: ./prepareDatabase
      run: |
        qmake prepareDatabase.pro
        make
    - name: make allocationTracker
      working-directory: ./allocationTracker
      run: make
    - name: make viwer
      working-directory: ./viewer
      run: |
        qmake viewer.pro
        make
        

