name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run build scripts
      run: | 
        sudo ./build-profiler.sh
        sudo ./build-viewer.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: viewer
        # A file, directory or wildcard pattern that describes what to upload
        path: viewer/viewer  
