name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run build scripts
      run: | 
        sudo apt update
        sudo ./install-dependencies-viewer.sh
        sudo ./install-dependencies-profiler.sh
        make
        tar -cvf perfMemPlus.tar viewer/viewer allocationTracker/ldlib.so prepareDatabase/prepareDatabase perfSqliteExport/exportToSqlite.py perfMemPlus perf setPerfEventPermissions.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: perfMemPlus
        # A file, directory or wildcard pattern that describes what to upload
        path: perfMemPlus.tar
          
          
